# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e3a56f051e744813f79a3f4c6bbf5edd9ab7c8e7698bbf038f53f8fe61685fe0c72601041e931088edcac719c3f39e91973da2326237f4e42bad0ab825b0c15

test:
  secret_key_base: 8b57f8b78efcc659b0ffd61e15c88a084ed3087a333bd933abd535c0fe8847959b8d614d918564a2d4de04cfa6779b4f80f2c40639873ff4c1e671b609634cbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
